trigger:
- master

jobs:
- job: 'Build'
  strategy:
    matrix:
      Windows:
        vmImage: windows-latest
      Linux:
        vmImage: ubuntu-latest
      MacOS:
        vmImage: macOS-latest
  pool:
    vmImage: $(vmImage)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: "Install Dependencies"

  - script: |
      yarn run compile
    displayName: 'Compile'

  - script: |
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
    displayName: 'Start xvfb'
    condition: eq(variables['Agent.OS'], 'Linux')

  - script: |
      yarn run test
    displayName: 'Test'
    env:
      DISPLAY: :10

- job: 'Release'
  dependsOn: 'Build'
  condition: and(and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags')), eq(variables['Agent.OS'], 'Linux'))

  steps:
  - script: |
      yarn package
    displayName: "Package VSIX"

  - task: GithubRelease@0
    displayName: 'Create Github Release'
    inputs:
      gitHubConnection: nzh21
      repositoryName: nzh63/systemtap-syntax
      assets:  $(Build.ArtifactStagingDirectory)/*.vsix

  - script: |
      npx vsce publish -p $TOKEN
    displayName: "Publish to Visual Studio Code Market"
    env:
      TOKEN: $(VSCODE_MARKETPLACE_TOKEN)
