export default [
    { "name": 'accept', "doc": 'syscall.accept sockfd:long addr_uaddr:long addrlen_uaddr:long name:string argstr:string' },
    { "name": 'accept4', "doc": 'syscall.accept4 sockfd:long addr_uaddr:long addrlen_uaddr:long flags:long name:string flags_str:string argstr:string' },
    { "name": 'access', "doc": 'syscall.access name:string pathname:string mode:long mode_str:string argstr:string $filename:long int $mode:long int' },
    { "name": 'acct', "doc": 'syscall.acct name:string filename:string argstr:string $name:long int' },
    { "name": 'add_key', "doc": 'syscall.add_key name:string type_uaddr:long description_uaddr:long payload_uaddr:long plen:long ringid:long argstr:string $_type:long int $_description:long int $_payload:long int $plen:long int $ringid:long int $ret:long int' },
    { "name": 'adjtimex', "doc": 'syscall.adjtimex name:string buf_uaddr:long buf_str:string argstr:string $txc_p:long int $ret:long int' },
    { "name": 'alarm', "doc": 'syscall.alarm name:string seconds:long argstr:string $seconds:long int' },
    { "name": 'arch_prctl', "doc": 'syscall.arch_prctl name:string code:long code_str:string addr:long argstr:string $code:int $addr:long unsigned int' },
    { "name": 'bdflush', "doc": 'syscall.bdflush name:string func:long data:long data_str:string argstr:string $func:long int $data:long int' },
    { "name": 'bind', "doc": 'syscall.bind sockfd:long my_addr_uaddr:long addrlen:long name:string uaddr_af:string uaddr_ip:string uaddr_ip_port:string uaddr_ipv6_flowinfo:string uaddr_ipv6_scope_id:string argstr:string' },
    { "name": 'bpf', "doc": 'syscall.bpf name:string cmd:long cmd_str:string attr_uaddr:long size:long argstr:string $cmd:long int $uattr:long int $size:long int' },
    { "name": 'brk', "doc": 'syscall.brk name:string brk:long argstr:string $brk:long int' },
    { "name": 'capget', "doc": 'syscall.capget name:string header_uaddr:long data_uaddr:long argstr:string $header:long int $dataptr:long int' },
    { "name": 'capset', "doc": 'syscall.capset name:string header_uaddr:long data_uaddr:long argstr:string $header:long int $data:long int' },
    { "name": 'chdir', "doc": 'syscall.chdir name:string path:string argstr:string $filename:long int' },
    { "name": 'chmod', "doc": 'syscall.chmod name:string path:string mode:long argstr:string $filename:long int $mode:long int' },
    { "name": 'chown', "doc": 'syscall.chown __nr:long name:string path:string owner:long group:long argstr:string $filename:long int $user:long int $group:long int' },
    { "name": 'chown16', "doc": 'syscall.chown16 name:string path:string owner:long group:long argstr:string $filename:long int $user:long int $group:long int' },
    { "name": 'chroot', "doc": 'syscall.chroot name:string path:string argstr:string $filename:long int' },
    { "name": 'clock_adjtime', "doc": 'syscall.clock_adjtime clk_id:long clk_id_str:string tx_uaddr:long tx_uaddr_str:string argstr:string name:string' },
    { "name": 'clock_getres', "doc": 'syscall.clock_getres name:string clk_id:long clk_id_str:string res_uaddr:long argstr:string' },
    { "name": 'clock_gettime', "doc": 'syscall.clock_gettime name:string clk_id:long clk_id_str:string tp_uaddr:long argstr:string' },
    { "name": 'clock_nanosleep', "doc": 'syscall.clock_nanosleep name:string clk_id:long clk_id_str:string flags:long flags_str:string req_uaddr:long req_str:string rem_uaddr:long argstr:string $which_clock:long int $flags:long int $rqtp:long int $rmtp:long int' },
    { "name": 'clock_settime', "doc": 'syscall.clock_settime clk_id:long clk_id_str:string tp_uaddr:long tp_uaddr_str:string argstr:string name:string' },
    { "name": 'clone', "doc": 'syscall.clone __nr:long name:string clone_flags:long stack_start:long parent_tid_uaddr:long child_tid_uaddr:long argstr:string $clone_flags:long unsigned int $stack_start:long unsigned int $stack_size:long unsigned int $parent_tidptr:int* $child_tidptr:int*' },
    { "name": 'close', "doc": 'syscall.close __nr:long name:string fd:long argstr:string $fd:long int' },
    { "name": 'compat_adjtimex', "doc": 'syscall.compat_adjtimex name:string buf_uaddr:long buf_str:string argstr:string $utp:struct compat_timex* $txc:struct timex' },
    { "name": 'compat_clock_nanosleep', "doc": 'syscall.compat_clock_nanosleep name:string clk_id:long clk_id_str:string flags:long flags_str:string req_uaddr:long req_str:string rem_uaddr:long argstr:string $which_clock:clockid_t $flags:int $rqtp:struct compat_timespec* $rmtp:struct compat_timespec* $in:struct timespec $out:struct timespec' },
    { "name": 'compat_execve', "doc": 'syscall.compat_execve name:string filename:string __argv:long args:string __envp:long env_str:string argstr:string $filename:char const* $argv:compat_uptr_t const* $envp:compat_uptr_t const*' },
    { "name": 'compat_fadvise64', "doc": 'syscall.compat_fadvise64 name:string fd:long offset:long len:long advice:long advice_str:string argstr:string $fd:int $offset_lo:unsigned int $offset_hi:unsigned int $len:size_t $advice:int' },
    { "name": 'compat_fadvise64_64', "doc": 'syscall.compat_fadvise64_64 name:string fd:long offset:long len:long advice:long advice_str:string argstr:string $fd:int $offset_low:__u32 $offset_high:__u32 $len_low:__u32 $len_high:__u32 $advice:int' },
    { "name": 'compat_fallocate', "doc": 'syscall.compat_fallocate name:string fd:long mode:long mode_str:string offset:long len:long argstr:string $fd:int $mode:int $offset_lo:unsigned int $offset_hi:unsigned int $len_lo:unsigned int $len_hi:unsigned int' },
    { "name": 'compat_ftruncate64', "doc": 'syscall.compat_ftruncate64 name:string fd:long length:long argstr:string $fd:unsigned int $offset_low:long unsigned int $offset_high:long unsigned int' },
    { "name": 'compat_futex', "doc": 'syscall.compat_futex name:string futex_uaddr:long op:long val:long utime_uaddr:long uaddr2_uaddr:long val3:long argstr:string $uaddr:long int $op:long int $val:long int $utime:long int $uaddr2:long int $val3:long int' },
    { "name": 'compat_futimesat', "doc": 'syscall.compat_futimesat __nr:long name:string dirfd:long dirfd_str:string filename_uaddr:long filename:string tvp_uaddr:long tvp_str:string argstr:string $dfd:unsigned int $filename:char const* $t:struct compat_timeval* $tv:struct timespec[]' },
    { "name": 'compat_getitimer', "doc": 'syscall.compat_getitimer name:string which:long value_uaddr:long argstr:string $which:long int $it:long int' },
    { "name": 'compat_lookup_dcookie', "doc": 'syscall.compat_lookup_dcookie name:string cookie:long buffer_uaddr:long len:long argstr:string $w0:long int $w1:long int $buf:long int $len:long int' },
    { "name": 'compat_nanosleep', "doc": 'syscall.compat_nanosleep name:string req_uaddr:long req_str:string rem_uaddr:long argstr:string $rqtp:struct compat_timespec* $rmtp:struct compat_timespec* $tu:struct timespec $rmt:struct timespec' },
    { "name": 'compat_ppoll', "doc": 'syscall.compat_ppoll name:string fds_uaddr:long nfds:long tsp:long tsp_str:string sigmask:long sigsetsize:long argstr:string $ufds:struct pollfd* $nfds:unsigned int $tsp:struct compat_timespec* $sigmask:compat_sigset_t const* $sigsetsize:compat_size_t $ss32:compat_sigset_t $ksigmask:sigset_t $sigsaved:sigset_t $ts:struct compat_timespec $end_time:struct timespec' },
    { "name": 'compat_pselect6', "doc": 'syscall.compat_pselect6 name:string nfds:long readfds:long writefds:long exceptfds:long timeout:long timeout_str:string sigmask:long argstr:string $n:int $inp:compat_ulong_t* $outp:compat_ulong_t* $exp:compat_ulong_t* $tsp:struct compat_timespec* $sig:void*' },
    { "name": 'compat_readahead', "doc": 'syscall.compat_readahead name:string fd:long offset:long count:long argstr:string $fd:int $off_lo:unsigned int $off_hi:unsigned int $count:size_t' },
    { "name": 'compat_recvmmsg', "doc": 'syscall.compat_recvmmsg name:string s:long mmsg_uaddr:long vlen:long flags:long flags_str:string timeout_uaddr:long timeout_str:string argstr:string $fd:int $mmsg:struct compat_mmsghdr* $vlen:unsigned int $flags:unsigned int $timeout:struct compat_timespec* $ktspec:struct timespec' },
    { "name": 'compat_rt_sigprocmask', "doc": 'syscall.compat_rt_sigprocmask name:string how:long how_str:string set_uaddr:long set_str:string oldset_uaddr:long sigsetsize:long argstr:string $how:long int $nset:long int $oset:long int $sigsetsize:long int' },
    { "name": 'compat_select', "doc": 'syscall.compat_select name:string n:long readfds_uaddr:long writefds_uaddr:long exceptfds_uaddr:long timeout_uaddr:long timeout_str:string argstr:string $n:int $inp:compat_ulong_t* $outp:compat_ulong_t* $exp:compat_ulong_t* $tvp:struct compat_timeval* $end_time:struct timespec $tv:struct compat_timeval' },
    { "name": 'compat_setitimer', "doc": 'syscall.compat_setitimer name:string which:long which_str:string value_uaddr:long value_str:string ovalue_uaddr:long argstr:string $which:long int $in:long int $out:long int' },
    { "name": 'compat_signalfd', "doc": 'syscall.compat_signalfd flags:long name:string argstr:string $ufd:long int $sigmask:long int $sigsetsize:long int $flags:long int' },
    { "name": 'compat_sys_msgctl', "doc": 'syscall.compat_sys_msgctl msqid:long cmd:long buf_uaddr:long name:string cmd_str:string argstr:string' },
    { "name": 'compat_sys_msgrcv', "doc": 'syscall.compat_sys_msgrcv msqid:long msgp_uaddr:long msgtyp:long msgsz:long msgflg:long name:string msgflg_str:string argstr:string' },
    { "name": 'compat_sys_msgsnd', "doc": 'syscall.compat_sys_msgsnd msqid:long msgp_uaddr:long msgsz:long msgflg:long name:string msgflg_str:string argstr:string' },
    { "name": 'compat_sys_recvmsg', "doc": 'syscall.compat_sys_recvmsg name:string s:long msg_uaddr:long flags:long flags_str:string argstr:string $call:int $args:u32* $a:u32[]' },
    { "name": 'compat_sys_semctl', "doc": 'syscall.compat_sys_semctl semid:long semnum:long cmd:long arg:long name:string cmdstr:string argstr:string' },
    { "name": 'compat_sys_semtimedop', "doc": 'syscall.compat_sys_semtimedop semid:long sops_uaddr:long nsops:long timeout_uaddr:long name:string timeout_str:string argstr:string' },
    { "name": 'compat_sys_sendmsg', "doc": 'syscall.compat_sys_sendmsg name:string s:long msg_uaddr:long flags:long flags_str:string argstr:string $call:int $args:u32* $a:u32[]' },
    { "name": 'compat_sys_shmat', "doc": 'syscall.compat_sys_shmat name:string shmid:long shmaddr_uaddr:long shmflg:long shmflg_str:string argstr:string $shmid:long int $shmaddr:long int $shmflg:long int' },
    { "name": 'compat_sys_shmctl', "doc": 'syscall.compat_sys_shmctl name:string shmid:long cmd:long cmd_str:string buf_uaddr:long argstr:string' },
    { "name": 'compat_sys_utimes', "doc": 'syscall.compat_sys_utimes name:string filename:string timeval:long tvp_uaddr_str:string argstr:string $filename:char const* $t:struct compat_timeval*' },
    { "name": 'compat_truncate64', "doc": 'syscall.compat_truncate64 name:string path_uaddr:long path:string length:long argstr:string $filename:char const* $offset_low:long unsigned int $offset_high:long unsigned int' },
    { "name": 'compat_utime', "doc": 'syscall.compat_utime name:string filename_uaddr:long filename:string buf_uaddr:long actime:long modtime:long argstr:string $filename:char const* $t:struct compat_utimbuf* $tv:struct timespec[]' },
    { "name": 'compat_utimensat', "doc": 'syscall.compat_utimensat name:string dfd:long dfd_str:string filename_uaddr:long filename:string tsp_uaddr:long tsp_str:string flags:long flags_str:string argstr:string $dfd:unsigned int $filename:char const* $t:struct compat_timespec* $flags:int $tv:struct timespec[]' },
    { "name": 'compat_vmsplice', "doc": 'syscall.compat_vmsplice name:string fd:long iov:long nr_segs:long flags:long flags_str:string argstr:string $fd:long int $iov32:long int $nr_segs:long int $flags:long int' },
    { "name": 'connect', "doc": 'syscall.connect sockfd:long serv_addr_uaddr:long addrlen:long name:string uaddr_af:string uaddr_ip:string uaddr_ip_port:string uaddr_ipv6_flowinfo:string uaddr_ipv6_scope_id:string argstr:string' },
    { "name": 'copy_file_range', "doc": 'syscall.copy_file_range name:string fd_in:long off_in:long fd_out:long off_out:long len:long flags:long argstr:string $fd_in:long int $off_in:long int $fd_out:long int $off_out:long int $len:long int $flags:long int $ret:long int' },
    { "name": 'creat', "doc": 'syscall.creat name:string mode:long pathname:string argstr:string $pathname:long int $mode:long int' },
    { "name": 'delete_module', "doc": 'syscall.delete_module name:string name_user:string flags:long flags_str:string argstr:string $name_user:long int $flags:long int' },
    { "name": 'dup', "doc": 'syscall.dup name:string oldfd:long argstr:string $fildes:long int' },
    { "name": 'dup2', "doc": 'syscall.dup2 name:string oldfd:long newfd:long flags:long flags_str:string argstr:string $oldfd:long int $newfd:long int' },
    { "name": 'dup3', "doc": 'syscall.dup3 __nr:long name:string oldfd:long newfd:long flags:long flags_str:string argstr:string $oldfd:long int $newfd:long int $flags:long int' },
    { "name": 'epoll_create', "doc": 'syscall.epoll_create size:long flags:long name:string argstr:string $flags:long int' },
    { "name": 'epoll_ctl', "doc": 'syscall.epoll_ctl name:string epfd:long op:long op_str:string fd:long event_uaddr:long argstr:string $epfd:long int $op:long int $fd:long int $event:long int' },
    { "name": 'epoll_pwait', "doc": 'syscall.epoll_pwait name:string epfd:long events_uaddr:long maxevents:long timeout:long sigmask_uaddr:long sigsetsize:long argstr:string $epfd:long int $events:long int $maxevents:long int $timeout:long int $sigmask:long int $sigsetsize:long int' },
    { "name": 'epoll_wait', "doc": 'syscall.epoll_wait __nr:long name:string epfd:long events_uaddr:long maxevents:long timeout:long argstr:string $epfd:long int $events:long int $maxevents:long int $timeout:long int' },
    { "name": 'eventfd', "doc": 'syscall.eventfd name:string count:long flags:long flags_str:string argstr:string $count:long int' },
    { "name": 'execve', "doc": 'syscall.execve name:string filename:string __argv:long args:string __envp:long env_str:string argstr:string $filename:long int $argv:long int $envp:long int' },
    { "name": 'exit', "doc": 'syscall.exit name:string status:long argstr:string $error_code:long int' },
    { "name": 'exit_group', "doc": 'syscall.exit_group name:string status:long argstr:string $error_code:long int' },
    { "name": 'faccessat', "doc": 'syscall.faccessat __nr:long name:string dirfd:long dirfd_str:string pathname:string mode:long mode_str:string argstr:string $dfd:long int $filename:long int $mode:long int' },
    { "name": 'fadvise64', "doc": 'syscall.fadvise64 name:string fd:long offset:long len:long advice:long advice_str:string argstr:string $fd:long int $offset:long long int $len:long int $advice:long int' },
    { "name": 'fadvise64_64', "doc": 'syscall.fadvise64_64 name:string fd:long offset:long len:long advice:long advice_str:string argstr:string $fd:long int $offset:long long int $len:long long int $advice:long int' },
    { "name": 'fallocate', "doc": 'syscall.fallocate name:string fd:long mode:long mode_str:string offset:long len:long argstr:string $fd:long int $mode:long int $offset:long long int $len:long long int' },
    { "name": 'fanotify_init', "doc": 'syscall.fanotify_init name:string flags:long flags_str:string event_f_flags:long event_f_flags_str:string argstr:string $flags:long int $event_f_flags:long int' },
    { "name": 'fanotify_mark', "doc": 'syscall.fanotify_mark fanotify_fd:long flags:long mask:long dirfd:long pathname:string name:string flags_str:string mask_str:string dirfd_str:string argstr:string $fanotify_fd:long int $flags:long int $dfd:long int $pathname:long int' },
    { "name": 'fchdir', "doc": 'syscall.fchdir name:string fd:long argstr:string $fd:long int' },
    { "name": 'fchmod', "doc": 'syscall.fchmod name:string fildes:long mode:long argstr:string $fd:long int $mode:long int' },
    { "name": 'fchmodat', "doc": 'syscall.fchmodat __nr:long name:string dirfd:long dirfd_str:string pathname:string mode:long argstr:string $dfd:long int $filename:long int $mode:long int' },
    { "name": 'fchown', "doc": 'syscall.fchown __nr:long name:string fd:long owner:long group:long argstr:string $fd:long int $user:long int $group:long int' },
    { "name": 'fchown16', "doc": 'syscall.fchown16 name:string fd:long owner:long group:long argstr:string $fd:long int $user:long int $group:long int' },
    { "name": 'fchownat', "doc": 'syscall.fchownat __nr:long name:string dirfd:long dirfd_str:string pathname:string owner:long group:long flags:long flags_str:string argstr:string $dfd:long int $filename:long int $user:long int $group:long int $flag:long int' },
    { "name": 'fcntl', "doc": 'syscall.fcntl name:string fd:long cmd:long cmd_str:string arg:long argstr:string' },
    { "name": 'fdatasync', "doc": 'syscall.fdatasync name:string fd:long argstr:string $fd:long int' },
    { "name": 'fgetxattr', "doc": 'syscall.fgetxattr name:string filedes:long name_str:string value_uaddr:long size:long argstr:string $fd:long int $name:long int $value:long int $size:long int' },
    { "name": 'finit_module', "doc": 'syscall.finit_module name:string fd:long uargs:string flags:long flags_str:string argstr:string $fd:long int $uargs:long int $flags:long int' },
    { "name": 'flistxattr', "doc": 'syscall.flistxattr name:string filedes:long list_uaddr:long size:long argstr:string $fd:long int $list:long int $size:long int' },
    { "name": 'flock', "doc": 'syscall.flock name:string fd:long operation:long argstr:string $fd:long int $cmd:long int' },
    { "name": 'fork', "doc": 'syscall.fork name:string argstr:string' },
    { "name": 'fremovexattr', "doc": 'syscall.fremovexattr name:string filedes:long name_uaddr:long name_str:string argstr:string $fd:long int $name:long int' },
    { "name": 'fsetxattr', "doc": 'syscall.fsetxattr name:string filedes:long name_uaddr:long name_str:string value_uaddr:long size:long value_str:string flags:long flags_str:string argstr:string $fd:long int $name:long int $value:long int $size:long int $flags:long int' },
    { "name": 'fstat', "doc": 'syscall.fstat name:string filedes:long buf_uaddr:long argstr:string' },
    { "name": 'fstatat', "doc": 'syscall.fstatat name:string dirfd:long dirfd_str:string path:string buf_uaddr:long flags:long flags_str:string argstr:string' },
    { "name": 'fstatfs', "doc": 'syscall.fstatfs name:string fd:long buf_uaddr:long argstr:string' },
    { "name": 'fstatfs64', "doc": 'syscall.fstatfs64 name:string fd:long sz:long buf_uaddr:long argstr:string' },
    { "name": 'fsync', "doc": 'syscall.fsync name:string fd:long argstr:string $fd:long int' },
    { "name": 'ftruncate', "doc": 'syscall.ftruncate name:string fd:long length:long argstr:string $fd:long int $length:long int' },
    { "name": 'futex', "doc": 'syscall.futex name:string futex_uaddr:long op:long val:long utime_uaddr:long uaddr2_uaddr:long val3:long argstr:string $uaddr:long int $op:long int $val:long int $utime:long int $uaddr2:long int $val3:long int' },
    { "name": 'futimesat', "doc": 'syscall.futimesat name:string dirfd:long dirfd_str:string filename_uaddr:long filename:string tvp_uaddr:long tvp_str:string argstr:string $dfd:long int $filename:long int $utimes:long int' },
    { "name": 'get_mempolicy', "doc": 'syscall.get_mempolicy name:string policy_uaddr:long nmask_uaddr:long maxnode:long addr:long flags:long flags_str:string argstr:string' },
    { "name": 'get_robust_list', "doc": 'syscall.get_robust_list name:string pid:long list_head_uaddr:long len_uaddr:long argstr:string $pid:long int $head_ptr:long int $len_ptr:long int' },
    { "name": 'get_thread_area', "doc": 'syscall.get_thread_area name:string u_info_uaddr:long u_info_str:string argstr:string $u_info:long int' },
    { "name": 'getcpu', "doc": 'syscall.getcpu name:string cpu_uaddr:long node_uaddr:long tcache_uaddr:long argstr:string $cpup:long int $nodep:long int $unused:long int' },
    { "name": 'getcwd', "doc": 'syscall.getcwd name:string buf_uaddr:long size:long argstr:string $buf:long int $size:long int' },
    { "name": 'getdents', "doc": 'syscall.getdents name:string fd:long dirp_uaddr:long count:long argstr:string' },
    { "name": 'getegid', "doc": 'syscall.getegid name:string argstr:string' },
    { "name": 'geteuid', "doc": 'syscall.geteuid name:string argstr:string' },
    { "name": 'getgid', "doc": 'syscall.getgid name:string argstr:string' },
    { "name": 'getgroups', "doc": 'syscall.getgroups name:string size:long list_uaddr:long argstr:string $gidsetsize:long int $grouplist:long int' },
    { "name": 'gethostname', "doc": 'syscall.gethostname name:string name_uaddr:long len:long argstr:string $name:long int $len:long int' },
    { "name": 'getitimer', "doc": 'syscall.getitimer name:string which:long value_uaddr:long argstr:string $which:long int $value:long int' },
    { "name": 'getpeername', "doc": 'syscall.getpeername s:long name_uaddr:long namelen_uaddr:long name:string argstr:string' },
    { "name": 'getpgid', "doc": 'syscall.getpgid __nr:long name:string pid:long argstr:string $pid:long int' },
    { "name": 'getpgrp', "doc": 'syscall.getpgrp name:string argstr:string' },
    { "name": 'getpid', "doc": 'syscall.getpid name:string argstr:string' },
    { "name": 'getppid', "doc": 'syscall.getppid name:string argstr:string' },
    { "name": 'getpriority', "doc": 'syscall.getpriority name:string which:long who:long argstr:string $which:long int $who:long int' },
    { "name": 'getrandom', "doc": 'syscall.getrandom name:string buf:string count:long flags:long flags_str:string argstr:string $buf:long int $count:long int $flags:long int' },
    { "name": 'getresgid', "doc": 'syscall.getresgid name:string rgid_uaddr:long egid_uaddr:long sgid_uaddr:long argstr:string $rgidp:long int $egidp:long int $sgidp:long int' },
    { "name": 'getresuid', "doc": 'syscall.getresuid name:string ruid_uaddr:long euid_uaddr:long suid_uaddr:long argstr:string $ruidp:long int $euidp:long int $suidp:long int' },
    { "name": 'getrlimit', "doc": 'syscall.getrlimit name:string resource:long rlim_uaddr:long argstr:string' },
    { "name": 'getrusage', "doc": 'syscall.getrusage name:string who:long who_str:string usage_uaddr:long argstr:string $who:long int $ru:long int' },
    { "name": 'getsid', "doc": 'syscall.getsid name:string pid:long argstr:string $pid:long int' },
    { "name": 'getsockname', "doc": 'syscall.getsockname s:long name_uaddr:long namelen_uaddr:long name:string argstr:string' },
    { "name": 'getsockopt', "doc": 'syscall.getsockopt fd:long level:long optname:long optval_uaddr:long optlen_uaddr:long name:string level_str:string optname_str:string argstr:string' },
    { "name": 'gettid', "doc": 'syscall.gettid name:string argstr:string' },
    { "name": 'gettimeofday', "doc": 'syscall.gettimeofday name:string tv_uaddr:long tz_uaddr:long argstr:string' },
    { "name": 'getuid', "doc": 'syscall.getuid name:string argstr:string' },
    { "name": 'getxattr', "doc": 'syscall.getxattr name:string path:string name_str:string value_uaddr:long size:long argstr:string $pathname:long int $name:long int $value:long int $size:long int' },
    { "name": 'init_module', "doc": 'syscall.init_module name:string umod_uaddr:long len:long uargs:string argstr:string $umod:long int $len:long int $uargs:long int' },
    { "name": 'inotify_add_watch', "doc": 'syscall.inotify_add_watch name:string fd:long mask:long mask_str:string path_uaddr:long path:string argstr:string $fd:long int $pathname:long int $mask:long int' },
    { "name": 'inotify_init', "doc": 'syscall.inotify_init name:string flags:long argstr:string' },
    { "name": 'inotify_rm_watch', "doc": 'syscall.inotify_rm_watch name:string fd:long wd:long argstr:string $fd:long int $wd:long int' },
    { "name": 'io_cancel', "doc": 'syscall.io_cancel name:string ctx_id:long iocb_uaddr:long result_uaddr:long argstr:string $ctx_id:long int $iocb:long int $result:long int' },
    { "name": 'io_destroy', "doc": 'syscall.io_destroy name:string ctx:long argstr:string $ctx:long int' },
    { "name": 'io_getevents', "doc": 'syscall.io_getevents name:string ctx_id:long events_uaddr:long timeout_uaddr:long nr:long min_nr:long timestr:string argstr:string' },
    { "name": 'io_setup', "doc": 'syscall.io_setup maxevents:long ctxp_uaddr:long argstr:string name:string' },
    { "name": 'io_submit', "doc": 'syscall.io_submit name:string ctx_id:long nr:long iocbpp_uaddr:long argstr:string' },
    { "name": 'ioctl', "doc": 'syscall.ioctl name:string fd:long request:long argp:long argstr:string' },
    { "name": 'ioperm', "doc": 'syscall.ioperm name:string from:long num:long turn_on:long argstr:string $from:long unsigned int $num:long unsigned int $turn_on:int' },
    { "name": 'iopl', "doc": 'syscall.iopl name:string level:long argstr:string $level:long int' },
    { "name": 'ioprio_get', "doc": 'syscall.ioprio_get name:string which:long which_str:string who:long argstr:string $which:long int $who:long int' },
    { "name": 'ioprio_set', "doc": 'syscall.ioprio_set name:string which:long which_str:string who:long ioprio:long ioprio_str:string argstr:string $which:long int $who:long int $ioprio:long int' },
    { "name": 'kcmp', "doc": 'syscall.kcmp name:string pid1:long pid2:long type:long type_str:string idx1:long idx2:long argstr:string $pid1:long int $pid2:long int $type:long int $idx1:long int $idx2:long int' },
    { "name": 'kexec_file_load', "doc": 'syscall.kexec_file_load name:string kernel_fd:long initrd_fd:long cmdline_len:long cmdline:string flags:long flags_str:string argstr:string $kernel_fd:long int $initrd_fd:long int $cmdline_len:long int $cmdline_ptr:long int $flags:long int' },
    { "name": 'kexec_load', "doc": 'syscall.kexec_load name:string entry:long nr_segments:long segments_uaddr:long flags:long flags_str:string argstr:string $entry:long int $nr_segments:long int $segments:long int $flags:long int' },
    { "name": 'keyctl', "doc": 'syscall.keyctl name:string option:long arg2:long arg3:long arg4:long arg5:long argstr:string' },
    { "name": 'kill', "doc": 'syscall.kill name:string pid:long sig:long sig_name:string argstr:string $pid:long int $sig:long int $ret:long int' },
    { "name": 'lchown', "doc": 'syscall.lchown __nr:long name:string path:string owner:long group:long argstr:string $filename:long int $user:long int $group:long int' },
    { "name": 'lchown16', "doc": 'syscall.lchown16 name:string path:string owner:long group:long argstr:string $filename:long int $user:long int $group:long int' },
    { "name": 'lgetxattr', "doc": 'syscall.lgetxattr name:string path:string name_str:string value_uaddr:long size:long argstr:string $pathname:long int $name:long int $value:long int $size:long int' },
    { "name": 'link', "doc": 'syscall.link name:string oldpath:string newpath:string argstr:string $oldname:long int $newname:long int' },
    { "name": 'linkat', "doc": 'syscall.linkat __nr:long name:string olddirfd:long olddirfd_str:string oldpath:string newdirfd:long newdirfd_str:string newpath:string flags:long flags_str:string argstr:string $olddfd:long int $oldname:long int $newdfd:long int $newname:long int $flags:long int' },
    { "name": 'listen', "doc": 'syscall.listen sockfd:long backlog:long name:string argstr:string' },
    { "name": 'listxattr', "doc": 'syscall.listxattr name:string list_uaddr:long size:long path_uaddr:long path:string argstr:string $pathname:long int $list:long int $size:long int' },
    { "name": 'llistxattr', "doc": 'syscall.llistxattr name:string list_uaddr:long size:long path_uaddr:long path:string argstr:string $pathname:long int $list:long int $size:long int' },
    { "name": 'llseek', "doc": 'syscall.llseek name:string fd:long offset_high:long offset_low:long result_uaddr:long whence:long whence_str:string argstr:string $fd:long int $offset_high:long int $offset_low:long int $result:long int $whence:long int' },
    { "name": 'lookup_dcookie', "doc": 'syscall.lookup_dcookie name:string cookie:long buffer_uaddr:long len:long argstr:string $cookie64:long long int $buf:long int $len:long int' },
    { "name": 'lremovexattr', "doc": 'syscall.lremovexattr name:string name_uaddr:long name_str:string path_uaddr:long path:string argstr:string $pathname:long int $name:long int' },
    { "name": 'lseek', "doc": 'syscall.lseek name:string fildes:long offset:long whence:long whence_str:string argstr:string $fd:long int $offset:long int $whence:long int' },
    { "name": 'lsetxattr', "doc": 'syscall.lsetxattr name:string path_uaddr:long path:string name_uaddr:long name_str:string value_uaddr:long size:long value_str:string flags:long flags_str:string argstr:string $pathname:long int $name:long int $value:long int $size:long int $flags:long int' },
    { "name": 'lstat', "doc": 'syscall.lstat name:string path:string buf_uaddr:long argstr:string' },
    { "name": 'madvise', "doc": 'syscall.madvise name:string start:long length:long advice:long advice_str:string argstr:string $start:long int $len_in:long int $behavior:long int' },
    { "name": 'mbind', "doc": 'syscall.mbind name:string start:long mode:long mode_str:string nmask_uaddr:long flags:long flags_str:string len:long maxnode:long argstr:string' },
    { "name": 'membarrier', "doc": 'syscall.membarrier name:string cmd:long cmd_str:string flags:long argstr:string $cmd:long int $flags:long int' },
    { "name": 'memfd_create', "doc": 'syscall.memfd_create name:string uname:string flags:long flags_str:string argstr:string $uname:long int $flags:long int' },
    { "name": 'migrate_pages', "doc": 'syscall.migrate_pages name:string pid:long old_nodes:long new_nodes:long maxnode:long argstr:string' },
    { "name": 'mincore', "doc": 'syscall.mincore name:string start:long length:long vec_uaddr:long argstr:string $start:long int $len:long int $vec:long int' },
    { "name": 'mkdir', "doc": 'syscall.mkdir name:string pathname_uaddr:long pathname:string mode:long argstr:string $pathname:long int $mode:long int' },
    { "name": 'mkdirat', "doc": 'syscall.mkdirat __nr:long name:string dirfd:long dirfd_str:string pathname:string mode:long argstr:string $dfd:long int $pathname:long int $mode:long int' },
    { "name": 'mknod', "doc": 'syscall.mknod name:string pathname:string mode:long mode_str:string dev:long argstr:string $filename:long int $mode:long int $dev:long int' },
    { "name": 'mknodat', "doc": 'syscall.mknodat __nr:long name:string dirfd:long dirfd_str:string pathname:string mode:long mode_str:string dev:long argstr:string $dfd:long int $filename:long int $mode:long int $dev:long int' },
    { "name": 'mlock', "doc": 'syscall.mlock name:string addr:long len:long argstr:string $start:long int $len:long int' },
    { "name": 'mlock2', "doc": 'syscall.mlock2 name:string addr:long len:long flags:long flags_str:string argstr:string $start:long int $len:long int $flags:long int' },
    { "name": 'mlockall', "doc": 'syscall.mlockall name:string flags:long flags_str:string argstr:string $flags:long int' },
    { "name": 'mmap2', "doc": 'syscall.mmap2 name:string start:long length:long prot:long prot_str:string flags:long flags_str:string fd:long pgoffset:long argstr:string $addr:long int $len:long int $prot:long int $flags:long int $fd:long int $pgoff:long int' },
    { "name": 'modify_ldt', "doc": 'syscall.modify_ldt name:string func:long ptr_uaddr:long bytecount:long argstr:string $func:long int $ptr:long int $bytecount:long int' },
    { "name": 'mount', "doc": 'syscall.mount name:string source:string target:string filesystemtype:string mountflags:long mountflags_str:string data:string argstr:string' },
    { "name": 'move_pages', "doc": 'syscall.move_pages name:string pages:long pid:long nodes:long status:long flags:long flags_str:string nr_pages:long argstr:string' },
    { "name": 'mprotect', "doc": 'syscall.mprotect name:string addr:long len:long prot:long prot_str:string argstr:string $start:long int $len:long int $prot:long int' },
    { "name": 'mq_getsetattr', "doc": 'syscall.mq_getsetattr name:string mqdes:long u_mqstat_uaddr:long u_omqstat_uaddr:long argstr:string' },
    { "name": 'mq_notify', "doc": 'syscall.mq_notify name:string mqdes:long notification_uaddr:long argstr:string' },
    { "name": 'mq_open', "doc": 'syscall.mq_open name:string name_uaddr:long filename:string u_attr_uaddr:long oflag:long oflag_str:string mode:long argstr:string' },
    { "name": 'mq_timedreceive', "doc": 'syscall.mq_timedreceive name:string mqdes:long msg_ptr_uaddr:long msg_prio_uaddr:long abs_timeout_uaddr:long msg_len:long argstr:string' },
    { "name": 'mq_timedsend', "doc": 'syscall.mq_timedsend name:string mqdes:long msg_ptr_uaddr:long msg_prio:long abs_timeout_uaddr:long msg_len:long argstr:string' },
    { "name": 'mq_unlink', "doc": 'syscall.mq_unlink name:string u_name_uaddr:long u_name:string argstr:string $u_name:long int' },
    { "name": 'mremap', "doc": 'syscall.mremap name:string old_address:long old_size:long new_size:long flags:long flags_str:string new_address:long argstr:string $addr:long int $old_len:long int $new_len:long int $flags:long int $new_addr:long int' },
    { "name": 'msgctl', "doc": 'syscall.msgctl __nr:long name:string msqid:long cmd:long cmd_str:string buf_uaddr:long argstr:string $msqid:long int $cmd:long int $buf:long int' },
    { "name": 'msgget', "doc": 'syscall.msgget name:string key:long key_str:string msgflg:long msgflg_str:string argstr:string $key:long int $msgflg:long int' },
    { "name": 'msgrcv', "doc": 'syscall.msgrcv name:string msqid:long msgp_uaddr:long msgsz:long msgtyp:long msgflg:long msgflg_str:string argstr:string $msqid:long int $msgp:long int $msgsz:long int $msgtyp:long int $msgflg:long int' },
    { "name": 'msgsnd', "doc": 'syscall.msgsnd name:string msqid:long msgp_uaddr:long msgsz:long msgflg:long msgflg_str:string argstr:string $msqid:long int $msgp:long int $msgsz:long int $msgflg:long int' },
    { "name": 'msync', "doc": 'syscall.msync name:string start:long length:long flags:long flags_str:string argstr:string $start:long int $len:long int $flags:long int' },
    { "name": 'munlock', "doc": 'syscall.munlock name:string addr:long len:long argstr:string $start:long int $len:long int' },
    { "name": 'munlockall', "doc": 'syscall.munlockall name:string argstr:string' },
    { "name": 'munmap', "doc": 'syscall.munmap name:string start:long length:long argstr:string $addr:long int $len:long int' },
    { "name": 'name_to_handle_at', "doc": 'syscall.name_to_handle_at name:string dfd:long dfd_str:string pathname:string handle_uaddr:long mnt_id_uaddr:long flags:long flags_str:string argstr:string $dfd:long int $name:long int $handle:long int $mnt_id:long int $flag:long int' },
    { "name": 'nanosleep', "doc": 'syscall.nanosleep name:string req_uaddr:long req_str:string rem_uaddr:long argstr:string $rqtp:long int $rmtp:long int' },
    { "name": 'ni_syscall', "doc": 'syscall.ni_syscall name:string argstr:string' },
    { "name": 'nice', "doc": 'syscall.nice name:string inc:long argstr:string $increment:long int' },
    { "name": 'open', "doc": 'syscall.open filename:string mode:long __nr:long name:string flags:long flags_str:string argstr:string $filename:long int $flags:long int $mode:long int' },
    { "name": 'open_by_handle_at', "doc": 'syscall.open_by_handle_at name:string mount_dfd:long mount_dfd_str:string handle_uaddr:long flags:long flags_str:string argstr:string $mountdirfd:long int $handle:long int $flags:long int' },
    { "name": 'openat', "doc": 'syscall.openat name:string dfd:long dfd_str:string filename:string flags:long flags_str:string mode:long argstr:string $dfd:long int $filename:long int $flags:long int $mode:long int' },
    { "name": 'pause', "doc": 'syscall.pause name:string argstr:string' },
    { "name": 'perf_event_open', "doc": 'syscall.perf_event_open name:string attr_uaddr:long pid:long cpu:long group_fd:long flags:long flags_str:string argstr:string $attr_uptr:long int $pid:long int $cpu:long int $group_fd:long int $flags:long int $ret:long int' },
    { "name": 'personality', "doc": 'syscall.personality name:string persona:long argstr:string $personality:long int' },
    { "name": 'pipe', "doc": 'syscall.pipe name:string flags:long flag_str:string fildes_uaddr:long pipe0:long pipe1:long argstr:string $fildes:long int' },
    { "name": 'pivot_root', "doc": 'syscall.pivot_root name:string new_root_str:string old_root_str:string argstr:string $new_root:long int $put_old:long int' },
    { "name": 'poll', "doc": 'syscall.poll name:string ufds_uaddr:long nfds:long timeout:long argstr:string $ufds:long int $nfds:long int $timeout_msecs:long int' },
    { "name": 'ppoll', "doc": 'syscall.ppoll name:string fds_uaddr:long nfds:long tsp:long tsp_str:string sigmask:long sigsetsize:long argstr:string $ufds:long int $nfds:long int $tsp:long int $sigmask:long int $sigsetsize:long int' },
    { "name": 'prctl', "doc": 'syscall.prctl name:string option:long arg2:long arg3:long arg4:long arg5:long argstr:string $option:long int $arg2:long int $arg3:long int $arg4:long int $arg5:long int' },
    { "name": 'pread', "doc": 'syscall.pread offset:long name:string fd:long buf_uaddr:long count:long argstr:string $fd:long int $buf:long int $count:long int $pos:long long int' },
    { "name": 'preadv', "doc": 'syscall.preadv fd:long vector_uaddr:long count:long offset:long argstr:string name:string $fd:long int $vec:long int $vlen:long int' },
    { "name": 'prlimit64', "doc": 'syscall.prlimit64 name:string pid:long resource:long resource_str:string new_rlim_uaddr:long new_rlim_str:string old_rlim_uaddr:long argstr:string $pid:long int $resource:long int $new_rlim:long int $old_rlim:long int' },
    { "name": 'process_vm_readv', "doc": 'syscall.process_vm_readv name:string pid:long local_iov_uaddr:long liovcnt:long remote_iov_uaddr:long riovcnt:long flags:long argstr:string' },
    { "name": 'process_vm_writev', "doc": 'syscall.process_vm_writev name:string pid:long local_iov_uaddr:long liovcnt:long remote_iov_uaddr:long riovcnt:long flags:long argstr:string' },
    { "name": 'pselect6', "doc": 'syscall.pselect6 name:string nfds:long readfds:long writefds:long exceptfds:long timeout:long timeout_str:string sigmask:long argstr:string $n:long int $inp:long int $outp:long int $exp:long int $tsp:long int $sig:long int' },
    { "name": 'ptrace', "doc": 'syscall.ptrace name:string request:long pid:long addr:long data:long argstr:string' },
    { "name": 'pwrite', "doc": 'syscall.pwrite name:string fd:long buf_uaddr:long count:long buf_str:string offset:long argstr:string $fd:long int $buf:long int $count:long int $pos:long long int' },
    { "name": 'pwritev', "doc": 'syscall.pwritev fd:long vector_uaddr:long count:long offset:long argstr:string name:string $fd:long int $vec:long int $vlen:long int' },
    { "name": 'quotactl', "doc": 'syscall.quotactl name:string cmd:long cmd_str:string special:long special_str:string id:long addr_uaddr:long argstr:string' },
    { "name": 'read', "doc": 'syscall.read name:string fd:long buf_uaddr:long count:long argstr:string $fd:long int $buf:long int $count:long int $ret:long int' },
    { "name": 'readahead', "doc": 'syscall.readahead name:string fd:long offset:long count:long argstr:string $fd:long int $offset:long long int $count:long int $ret:long int' },
    { "name": 'readdir', "doc": 'syscall.readdir name:string fd:long dirent:long count:long argstr:string' },
    { "name": 'readlink', "doc": 'syscall.readlink name:string path:string buf_uaddr:long bufsiz:long argstr:string $path:long int $buf:long int $bufsiz:long int' },
    { "name": 'readlinkat', "doc": 'syscall.readlinkat __nr:long name:string dfd:long dfd_str:string buf_uaddr:long bufsiz:long path:string argstr:string $dfd:long int $pathname:long int $buf:long int $bufsiz:long int' },
    { "name": 'readv', "doc": 'syscall.readv name:string vector_uaddr:long count:long fd:long argstr:string $fd:long int $vec:long int $vlen:long int' },
    { "name": 'reboot', "doc": 'syscall.reboot name:string magic:long magic_str:string magic2:long magic2_str:string flag:long flag_str:string arg_uaddr:long argstr:string $magic1:long int $magic2:long int $cmd:long int $arg:long int $ret:long int' },
    { "name": 'recv', "doc": 'syscall.recv s:long buf_uaddr:long len:long flags:long name:string flags_str:string argstr:string' },
    { "name": 'recvfrom', "doc": 'syscall.recvfrom s:long buf_uaddr:long len:long flags:long addr_uaddr:long addrlen_uaddr:long name:string flags_str:string argstr:string' },
    { "name": 'recvmmsg', "doc": 'syscall.recvmmsg name:string s:long mmsg_uaddr:long vlen:long flags:long flags_str:string timeout_uaddr:long timeout_str:string argstr:string $fd:long int $mmsg:long int $vlen:long int $flags:long int $timeout:long int' },
    { "name": 'recvmsg', "doc": 'syscall.recvmsg s:long msg_uaddr:long flags:long name:string flags_str:string argstr:string' },
    { "name": 'remap_file_pages', "doc": 'syscall.remap_file_pages name:string start:long size:long prot:long prot_str:string pgoff:long flags:long flags_str:string argstr:string $start:long int $size:long int $prot:long int $pgoff:long int $flags:long int' },
    { "name": 'removexattr', "doc": 'syscall.removexattr name:string path:string name_str:string argstr:string $pathname:long int $name:long int' },
    { "name": 'rename', "doc": 'syscall.rename name:string oldpath:string newpath:string argstr:string $oldname:long int $newname:long int' },
    { "name": 'renameat', "doc": 'syscall.renameat __nr:long name:string olddfd:long olddfd_str:string oldname:long oldname_str:string newdfd:long newdfd_str:string newname:long newname_str:string argstr:string $olddfd:long int $oldname:long int $newdfd:long int $newname:long int' },
    { "name": 'renameat2', "doc": 'syscall.renameat2 __nr:long name:string olddfd:long olddfd_str:string oldname:long oldname_str:string newdfd:long newdfd_str:string newname:long newname_str:string flags:long flags_str:string argstr:string $olddfd:long int $oldname:long int $newdfd:long int $newname:long int $flags:long int $ret:long int' },
    { "name": 'request_key', "doc": 'syscall.request_key name:string type_uaddr:long type_str:string description_uaddr:long description_str:string callout_info_uaddr:long destringid:long argstr:string $_type:long int $_description:long int $_callout_info:long int $destringid:long int $ret:long int' },
    { "name": 'restart_syscall', "doc": 'syscall.restart_syscall name:string argstr:string' },
    { "name": 'rmdir', "doc": 'syscall.rmdir name:string pathname:string argstr:string $pathname:long int' },
    { "name": 'rt_sigaction', "doc": 'syscall.rt_sigaction name:string sig:long sig_str:string act_uaddr:long act_str:string oact_uaddr:long sigsetsize:long argstr:string $sig:long int $act:long int $oact:long int $sigsetsize:long int' },
    { "name": 'rt_sigaction32', "doc": 'syscall.rt_sigaction32 name:string sig:long sig_str:string act_uaddr:long act_str:string oact_uaddr:long sigsetsize:long argstr:string $sig:long int $act:long int $oact:long int $sigsetsize:long int' },
    { "name": 'rt_sigpending', "doc": 'syscall.rt_sigpending name:string set_uaddr:long sigsetsize:long argstr:string $uset:long int $sigsetsize:long int' },
    { "name": 'rt_sigprocmask', "doc": 'syscall.rt_sigprocmask name:string how:long how_str:string set_uaddr:long oldset_uaddr:long set_str:string sigsetsize:long argstr:string $how:long int $nset:long int $oset:long int $sigsetsize:long int' },
    { "name": 'rt_sigqueueinfo', "doc": 'syscall.rt_sigqueueinfo name:string pid:long sig:long sig_name:string uinfo_uaddr:long siginfo_str:string argstr:string $pid:long int $sig:long int $uinfo:long int' },
    { "name": 'rt_sigreturn', "doc": 'syscall.rt_sigreturn name:string argstr:string $set:sigset_t' },
    { "name": 'rt_sigsuspend', "doc": 'syscall.rt_sigsuspend name:string set_uaddr:long sigsetsize:long set_str:string argstr:string $unewset:long int $sigsetsize:long int' },
    { "name": 'rt_sigtimedwait', "doc": 'syscall.rt_sigtimedwait name:string uthese_uaddr:long uinfo_uaddr:long uts_uaddr:long sigsetsize:long uthese_str:string uinfo_str:string uts_str:string argstr:string $uthese:long int $uinfo:long int $uts:long int $sigsetsize:long int' },
    { "name": 'rt_tgsigqueueinfo', "doc": 'syscall.rt_tgsigqueueinfo name:string tgid:long tid:long sig:long sig_str:string uinfo_uaddr:long uinfo_str:string argstr:string $tgid:long int $pid:long int $sig:long int $uinfo:long int' },
    { "name": 'sched_get_priority_max', "doc": 'syscall.sched_get_priority_max name:string policy:long policy_str:string argstr:string $policy:long int' },
    { "name": 'sched_get_priority_min', "doc": 'syscall.sched_get_priority_min name:string policy:long policy_str:string argstr:string $policy:long int' },
    { "name": 'sched_getaffinity', "doc": 'syscall.sched_getaffinity name:string pid:long len:long mask_uaddr:long argstr:string' },
    { "name": 'sched_getattr', "doc": 'syscall.sched_getattr name:string pid:long sched_attr_uaddr:long sched_attr_str:string size:long flags:long argstr:string $pid:long int $uattr:long int $size:long int $flags:long int' },
    { "name": 'sched_getparam', "doc": 'syscall.sched_getparam name:string pid:long p_uaddr:long argstr:string $pid:long int $param:long int' },
    { "name": 'sched_getscheduler', "doc": 'syscall.sched_getscheduler name:string pid:long argstr:string $pid:long int' },
    { "name": 'sched_rr_get_interval', "doc": 'syscall.sched_rr_get_interval name:string pid:long tp_uaddr:long argstr:string $pid:long int $interval:long int' },
    { "name": 'sched_setaffinity', "doc": 'syscall.sched_setaffinity name:string pid:long len:long mask_uaddr:long argstr:string' },
    { "name": 'sched_setattr', "doc": 'syscall.sched_setattr name:string pid:long sched_attr_uaddr:long sched_attr_str:string flags:long argstr:string $pid:long int $uattr:long int $flags:long int' },
    { "name": 'sched_setparam', "doc": 'syscall.sched_setparam name:string pid:long p_uaddr:long argstr:string $pid:long int $param:long int' },
    { "name": 'sched_setscheduler', "doc": 'syscall.sched_setscheduler name:string pid:long policy:long policy_str:string p_uaddr:long argstr:string $pid:long int $policy:long int $param:long int' },
    { "name": 'sched_yield', "doc": 'syscall.sched_yield name:string argstr:string' },
    { "name": 'seccomp', "doc": 'syscall.seccomp name:string op:long op_str:string flags:long flags_str:string uargs_uaddr:long argstr:string $op:long int $flags:long int $uargs:long int' },
    { "name": 'select', "doc": 'syscall.select name:string n:long readfds_uaddr:long writefds_uaddr:long exceptfds_uaddr:long timeout_uaddr:long timeout_str:string argstr:string $n:long int $inp:long int $outp:long int $exp:long int $tvp:long int' },
    { "name": 'semctl', "doc": 'syscall.semctl name:string semid:long semnum:long cmd:long cmdstr:string arg:long argstr:string $semid:long int $semnum:long int $cmd:long int $arg:long int' },
    { "name": 'semget', "doc": 'syscall.semget name:string key:long key_str:string nsems:long semflg:long semflg_str:string argstr:string $key:long int $nsems:long int $semflg:long int' },
    { "name": 'semop', "doc": 'syscall.semop semid:long sops_uaddr:long nsops:long name:string argstr:string' },
    { "name": 'semtimedop', "doc": 'syscall.semtimedop __nr:long name:string semid:long sops_uaddr:long nsops:long timeout_uaddr:long timeout_str:string argstr:string $semid:long int $tsops:long int $nsops:long int $timeout:long int $ret:long int' },
    { "name": 'send', "doc": 'syscall.send s:long buf_uaddr:long len:long flags:long name:string flags_str:string buf:string argstr:string' },
    { "name": 'sendfile', "doc": 'syscall.sendfile name:string out_fd:long in_fd:long offset_uaddr:long count:long argstr:string $out_fd:long int $in_fd:long int $offset:long int $count:long int' },
    { "name": 'sendmmsg', "doc": 'syscall.sendmmsg s:long mmsg_uaddr:long vlen:long flags:long name:string flags_str:string argstr:string' },
    { "name": 'sendmsg', "doc": 'syscall.sendmsg s:long msg_uaddr:long flags:long name:string flags_str:string argstr:string' },
    { "name": 'sendto', "doc": 'syscall.sendto s:long buf_uaddr:long len:long flags:long to_uaddr:long tolen:long name:string flags_str:string buf:string to_str:string argstr:string' },
    { "name": 'set_mempolicy', "doc": 'syscall.set_mempolicy name:string mode:long mode_str:string nmask_uaddr:long maxnode:long argstr:string' },
    { "name": 'set_robust_list', "doc": 'syscall.set_robust_list name:string list_head_uaddr:long len:long argstr:string $head:long int $len:long int' },
    { "name": 'set_thread_area', "doc": 'syscall.set_thread_area name:string u_info_uaddr:long u_info_str:string argstr:string $u_info:long int' },
    { "name": 'set_tid_address', "doc": 'syscall.set_tid_address name:string tidptr_uaddr:long argstr:string $tidptr:long int' },
    { "name": 'setdomainname', "doc": 'syscall.setdomainname name:string domainname_uaddr:long domainname_str:string len:long argstr:string $name:long int $len:long int' },
    { "name": 'setfsgid', "doc": 'syscall.setfsgid name:string fsgid:long argstr:string $gid:long int' },
    { "name": 'setfsuid', "doc": 'syscall.setfsuid name:string fsuid:long argstr:string $uid:long int' },
    { "name": 'setgid', "doc": 'syscall.setgid name:string gid:long argstr:string $gid:long int' },
    { "name": 'setgroups', "doc": 'syscall.setgroups name:string size:long list_uaddr:long argstr:string $gidsetsize:long int $grouplist:long int' },
    { "name": 'sethostname', "doc": 'syscall.sethostname name:string hostname_uaddr:long name_str:string len:long argstr:string $name:long int $len:long int' },
    { "name": 'setitimer', "doc": 'syscall.setitimer name:string which:long which_str:string value_uaddr:long value_str:string ovalue_uaddr:long argstr:string $which:long int $value:long int $ovalue:long int' },
    { "name": 'setns', "doc": 'syscall.setns name:string fd:long nstype:long nstype_str:string argstr:string $fd:long int $nstype:long int' },
    { "name": 'setpgid', "doc": 'syscall.setpgid name:string pid:long pgid:long argstr:string $pid:long int $pgid:long int' },
    { "name": 'setpriority', "doc": 'syscall.setpriority name:string which:long which_str:string who:long prio:long argstr:string $which:long int $who:long int $niceval:long int' },
    { "name": 'setregid', "doc": 'syscall.setregid __nr:long name:string rgid:long egid:long argstr:string $rgid:long int $egid:long int' },
    { "name": 'setregid16', "doc": 'syscall.setregid16 name:string rgid:long egid:long argstr:string $rgid:long int $egid:long int' },
    { "name": 'setresgid', "doc": 'syscall.setresgid __nr:long name:string rgid:long egid:long sgid:long argstr:string $rgid:long int $egid:long int $sgid:long int' },
    { "name": 'setresgid16', "doc": 'syscall.setresgid16 name:string rgid:long egid:long sgid:long argstr:string $rgid:long int $egid:long int $sgid:long int' },
    { "name": 'setresuid', "doc": 'syscall.setresuid __nr:long name:string ruid:long euid:long suid:long argstr:string $ruid:long int $euid:long int $suid:long int' },
    { "name": 'setresuid16', "doc": 'syscall.setresuid16 name:string ruid:long euid:long suid:long argstr:string $ruid:long int $euid:long int $suid:long int' },
    { "name": 'setreuid', "doc": 'syscall.setreuid __nr:long name:string ruid:long euid:long argstr:string $ruid:long int $euid:long int' },
    { "name": 'setreuid16', "doc": 'syscall.setreuid16 name:string ruid:long euid:long argstr:string $ruid:long int $euid:long int' },
    { "name": 'setrlimit', "doc": 'syscall.setrlimit name:string resource:long resource_str:string rlim_uaddr:long rlim_str:string argstr:string' },
    { "name": 'setsid', "doc": 'syscall.setsid name:string argstr:string' },
    { "name": 'setsockopt', "doc": 'syscall.setsockopt fd:long level:long optname:long optval_uaddr:long optlen:long name:string level_str:string optname_str:string argstr:string' },
    { "name": 'settimeofday', "doc": 'syscall.settimeofday name:string tv_uaddr:long tv_str:string tz_uaddr:long tz_str:string argstr:string $tv:long int $tz:long int' },
    { "name": 'settimeofday32', "doc": 'syscall.settimeofday32 name:string tv_uaddr:long tv_str:string tz_uaddr:long tz_str:string argstr:string $tv:struct compat_timeval* $tz:struct timezone* $kts:struct timespec $ktz:struct timezone' },
    { "name": 'setuid', "doc": 'syscall.setuid name:string uid:long argstr:string $uid:long int' },
    { "name": 'setxattr', "doc": 'syscall.setxattr name:string path_uaddr:long path:string name_uaddr:long name_str:string value_uaddr:long value_str:string size:long flags:long flags_str:string argstr:string $pathname:long int $name:long int $value:long int $size:long int $flags:long int' },
    { "name": 'sgetmask', "doc": 'syscall.sgetmask name:string argstr:string' },
    { "name": 'shmat', "doc": 'syscall.shmat name:string shmid:long shmaddr_uaddr:long shmflg:long shmflg_str:string argstr:string $shmid:long int $shmaddr:long int $shmflg:long int' },
    { "name": 'shmctl', "doc": 'syscall.shmctl name:string shmid:long cmd:long cmd_str:string buf_uaddr:long argstr:string $shmid:long int $cmd:long int $buf:long int' },
    { "name": 'shmdt', "doc": 'syscall.shmdt name:string shmaddr_uaddr:long argstr:string $shmaddr:long int' },
    { "name": 'shmget', "doc": 'syscall.shmget name:string key:long size:long shmflg:long shmflg_str:string argstr:string $key:long int $size:long int $shmflg:long int' },
    { "name": 'shutdown', "doc": 'syscall.shutdown s:long how:long name:string how_str:string argstr:string' },
    { "name": 'sigaction32', "doc": 'syscall.sigaction32 name:string sig:long sig_str:string act_uaddr:long act_str:string oact_uaddr:long argstr:string $sig:long int $act:long int $oact:long int' },
    { "name": 'sigaltstack', "doc": 'syscall.sigaltstack name:string uss_uaddr:long uss_str:string uoss_uaddr:long argstr:string' },
    { "name": 'signal', "doc": 'syscall.signal name:string sig:long sig_str:string handler:long handler_str:string argstr:string $sig:long int $handler:long int' },
    { "name": 'signalfd', "doc": 'syscall.signalfd flags:long name:string argstr:string $ufd:long int $user_mask:long int $sizemask:long int $flags:long int' },
    { "name": 'sigpending', "doc": 'syscall.sigpending name:string set:long argstr:string' },
    { "name": 'sigprocmask', "doc": 'syscall.sigprocmask name:string how:long how_str:string set_uaddr:long oldset_uaddr:long argstr:string $how:long int $nset:long int $oset:long int' },
    { "name": 'sigreturn', "doc": 'syscall.sigreturn name:string argstr:string $set:sigset_t $ax:unsigned int' },
    { "name": 'sigsuspend', "doc": 'syscall.sigsuspend name:string mask:long mask_str:string argstr:string $unused1:long int $unused2:long int $mask:long int' },
    { "name": 'socket', "doc": 'syscall.socket family:long type:long protocol:long name:string family_str:string type_str:string protocol_str:string argstr:string' },
    { "name": 'socketpair', "doc": 'syscall.socketpair family:long type:long protocol:long sv_uaddr:long name:string family_str:string type_str:string protocol_str:string argstr:string' },
    { "name": 'splice', "doc": 'syscall.splice name:string fd_in:long off_in:long fd_out:long off_out:long len:long flags:long flags_str:string argstr:string $fd_in:long int $off_in:long int $fd_out:long int $off_out:long int $len:long int $flags:long int' },
    { "name": 'ssetmask', "doc": 'syscall.ssetmask name:string newmask:long newmask_str:string argstr:string $newmask:long int' },
    { "name": 'stat', "doc": 'syscall.stat name:string filename_uaddr:long filename:string buf_uaddr:long argstr:string' },
    { "name": 'statfs', "doc": 'syscall.statfs name:string buf_uaddr:long path:string argstr:string' },
    { "name": 'statfs64', "doc": 'syscall.statfs64 name:string path:string sz:long buf_uaddr:long argstr:string' },
    { "name": 'stime', "doc": 'syscall.stime name:string t_uaddr:long argstr:string' },
    { "name": 'swapoff', "doc": 'syscall.swapoff name:string path_uaddr:long path:string argstr:string $specialfile:long int' },
    { "name": 'swapon', "doc": 'syscall.swapon name:string path_uaddr:long path:string swapflags:long swapflags_str:string argstr:string $specialfile:long int $swap_flags:long int' },
    { "name": 'symlink', "doc": 'syscall.symlink name:string oldpath:string newpath:string argstr:string $oldname:long int $newname:long int' },
    { "name": 'symlinkat', "doc": 'syscall.symlinkat __nr:long name:string oldname:long oldname_str:string newdfd:long newdfd_str:string newname:long newname_str:string argstr:string $oldname:long int $newdfd:long int $newname:long int' },
    { "name": 'sync', "doc": 'syscall.sync name:string argstr:string $nowait:int $wait:int' },
    { "name": 'sync_file_range', "doc": 'syscall.sync_file_range name:string fd:long offset:long nbytes:long flags:long flags_str:string argstr:string $fd:long int $offset:long long int $nbytes:long long int $flags:long int' },
    { "name": 'syncfs', "doc": 'syscall.syncfs name:string fd:long argstr:string $fd:long int' },
    { "name": 'sysctl', "doc": 'syscall.sysctl name:string args:long argstr:string $args:long int' },
    { "name": 'sysfs', "doc": 'syscall.sysfs name:string option:long arg1:long arg2:long argstr:string $option:long int $arg1:long int $arg2:long int' },
    { "name": 'sysinfo', "doc": 'syscall.sysinfo name:string info_uaddr:long info_str:string argstr:string $info:long int' },
    { "name": 'syslog', "doc": 'syscall.syslog name:string type:long bufp_uaddr:long len:long argstr:string $type:long int $buf:long int $len:long int' },
    { "name": 'tee', "doc": 'syscall.tee name:string fdin:long fdout:long len:long flags:long argstr:string $fdin:long int $fdout:long int $len:long int $flags:long int' },
    { "name": 'tgkill', "doc": 'syscall.tgkill name:string tgid:long pid:long sig:long sig_str:string argstr:string $tgid:long int $pid:long int $sig:long int' },
    { "name": 'time', "doc": 'syscall.time name:string t_uaddr:long argstr:string' },
    { "name": 'timer_create', "doc": 'syscall.timer_create name:string clockid:long clockid_str:string evp_uaddr:long timerid_uaddr:long argstr:string' },
    { "name": 'timer_delete', "doc": 'syscall.timer_delete name:string timerid:long argstr:string $timer_id:long int' },
    { "name": 'timer_getoverrun', "doc": 'syscall.timer_getoverrun name:string timerid:long argstr:string $timer_id:long int' },
    { "name": 'timer_gettime', "doc": 'syscall.timer_gettime name:string timerid:long value_uaddr:long argstr:string' },
    { "name": 'timer_settime', "doc": 'syscall.timer_settime name:string timerid:long flags:long value_uaddr:long ovalue_uaddr:long value_str:string argstr:string' },
    { "name": 'timerfd_create', "doc": 'syscall.timerfd_create name:string clockid:long clockid_str:string flags:long flags_str:string argstr:string $clockid:long int $flags:long int' },
    { "name": 'timerfd_gettime', "doc": 'syscall.timerfd_gettime name:string fd:long value_uaddr:long argstr:string $ufd:long int $otmr:long int' },
    { "name": 'timerfd_settime', "doc": 'syscall.timerfd_settime name:string fd:long flags:long flags_str:string value_uaddr:long ovalue_uaddr:long value_str:string argstr:string $ufd:long int $flags:long int $utmr:long int $otmr:long int' },
    { "name": 'times', "doc": 'syscall.times name:string buf_uaddr:long buf_str:string argstr:string' },
    { "name": 'tkill', "doc": 'syscall.tkill name:string pid:long sig:long sig_str:string argstr:string $pid:long int $sig:long int' },
    { "name": 'truncate', "doc": 'syscall.truncate length:long name:string path_uaddr:long path:string argstr:string $path:long int $length:long int' },
    { "name": 'umask', "doc": 'syscall.umask name:string mask:long argstr:string $mask:long int' },
    { "name": 'umount', "doc": 'syscall.umount target:string flags:long flags_str:string argstr:string name:string $name:long int' },
    { "name": 'uname', "doc": 'syscall.uname name:string name_uaddr:long argstr:string $name:long int' },
    { "name": 'unlink', "doc": 'syscall.unlink name:string pathname_uaddr:long pathname:string argstr:string $pathname:long int' },
    { "name": 'unlinkat', "doc": 'syscall.unlinkat name:string dfd:long dfd_str:string pathname:long pathname_str:string flag:long flag_str:string argstr:string $dfd:long int $pathname:long int $flag:long int' },
    { "name": 'unshare', "doc": 'syscall.unshare name:string unshare_flags:long unshare_flags_str:string argstr:string $unshare_flags:long int' },
    { "name": 'uselib', "doc": 'syscall.uselib name:string library_uaddr:long library:string argstr:string $library:long int' },
    { "name": 'userfaultfd', "doc": 'syscall.userfaultfd name:string flags:long flags_str:string argstr:string $flags:long int' },
    { "name": 'ustat', "doc": 'syscall.ustat name:string dev:long ubuf_uaddr:long argstr:string $dev:long int $ubuf:long int $ret:long int' },
    { "name": 'ustat32', "doc": 'syscall.ustat32 name:string dev:long ubuf_uaddr:long argstr:string $dev:unsigned int $u:struct compat_ustat* $tmp:struct compat_ustat $sbuf:struct kstatfs' },
    { "name": 'utime', "doc": 'syscall.utime name:string filename_uaddr:long filename:string buf_uaddr:long actime:long modtime:long argstr:string $filename:long int $times:long int' },
    { "name": 'utimensat', "doc": 'syscall.utimensat name:string dfd:long dfd_str:string filename_uaddr:long filename:string tsp_uaddr:long tsp_str:string flags:long flags_str:string argstr:string $dfd:long int $filename:long int $utimes:long int $flags:long int' },
    { "name": 'utimes', "doc": 'syscall.utimes name:string filename_uaddr:long filename:string tvp_uaddr:long tvp_uaddr_str:string argstr:string $filename:long int $utimes:long int' },
    { "name": 'vfork', "doc": 'syscall.vfork name:string argstr:string' },
    { "name": 'vhangup', "doc": 'syscall.vhangup name:string argstr:string' },
    { "name": 'vm86_warning', "doc": 'syscall.vm86_warning name:string argstr:string $lastcomm:char[]' },
    { "name": 'vmsplice', "doc": 'syscall.vmsplice name:string fd:long iov:long nr_segs:long flags:long flags_str:string argstr:string $fd:long int $iov:long int $nr_segs:long int $flags:long int' },
    { "name": 'wait4', "doc": 'syscall.wait4 name:string pid:long status_uaddr:long options:long options_str:string rusage_uaddr:long argstr:string $stat_addr:long int $options:long int $ru:long int' },
    { "name": 'waitid', "doc": 'syscall.waitid name:string which:long which_str:string pid:long infop_uaddr:long options:long options_str:string rusage_uaddr:long argstr:string $which:long int $options:long int' },
    { "name": 'waitpid', "doc": 'syscall.waitpid name:string pid:long status_uaddr:long options:long options_str:string argstr:string' },
    { "name": 'write', "doc": 'syscall.write name:string fd:long buf_uaddr:long count:long buf_str:string argstr:string $fd:long int $buf:long int $count:long int $ret:long int' },
    { "name": 'writev', "doc": 'syscall.writev name:string vector_uaddr:long count:long fd:long argstr:string $fd:long int $vec:long int $vlen:long int' }
];
